<?php
    require_once("../php/menu.php")
    ?>

<link rel="stylesheet" href="index.css">

<div class="col-12 pele">
<p class="header-privacy">Privacy Policy</p>
<p>The Privacy Policy (hereinafter "the policy") provided below is with respect to our use and protection of any personal information/data you provide to us through our website. HT Media Limited (HTML) is the sole owner of the website Jobs Made Easy (hereinafter "website"). The Policy is applicable to the website. You may be required to provide personally identifiable information at several different points on our website. By accepting the policy at the time of registration, you expressly approve and consent to our collection, storage, use and disclosure of your personal information as described in this Policy</p><br><br>
<p><strong>Information Collection</strong></p>
<p>When you visit/surf our website, certain personal information about you such as your IP Address, etc. may be automatically stored with us. However, if you choose to avail of certain services on our website, you shall be required to provide certain personal information for the registration and/or access to such services/web pages. Such information may include, without limitation, your name, email address, contact address, mobile/telephone number(s), sex, age, occupation, interests, credit card information, billing information, financial information, content, IP address, standard web log information, information about your computer hardware and software and such other information as may be required for your interaction with the services and from which your identity is discernible. We may also collect demographic information that is not unique to you such as code, preferences, favorites, etc. Further, sometimes you may be asked to provide descriptive, cultural, preferential and social &amp; life style information. In addition to the above we may indirectly also collect information about you when you use certain third party services available on our website. We may also collect certain information about the use of our website by you, such as the services you access/use or areas you visit.</p><br><br>
<p><strong>Use</strong></p>
<p>If you choose to provide us with the above mentioned information, you consent to the use, transfer, processing and storage of the information so provided by you on our servers. The information provided by you shall not be given to third parties (third parties for this purpose do not include our group / holding / subsidiary companies and or our service partners / associates) for marketing purposes and other related activities without your prior consent. Though if you choose to make your profile visible, all information pertaining to your profile will be visible to third parties.</p><br><br>
<p><strong>The information provided by you shall be used by us to:</strong></p>
<ol>
	<li>Improve our website and enable us to provide you the most user-friendly experience which is safe, smooth and customized</li>
	<li>Improve and customize our services, content and other commercial / non-commercial features on the website</li>
	<li>Contact you to get your opinion on our current products and services or possible new products and/or services that may be offered by us</li>
	<li>Send you information on our products, services, special deals, promotions</li>
	<li>Ask you to send feedback on any or all of our services</li>
	<li>Send you marketing/promotional communications (If you do not wish to receive such marketing/promotional communications from us you may indicate your preferences at the time of registration or by following the instructions provided on the website or by providing instructions to this effect)</li>
	<li>Create various surveys and analysis in form of reports</li>
	<li>Send newsletter(s) to you (Provided you subscribe to the same)</li>
	<li>Send you service-related announcements on rare occasions when it is necessary to do so</li>
	<li>Provide you the opportunity to participate in contests or surveys on our website (If you participate, we may request certain additional personally identifiable information from you. Moreover, participation in these surveys or contests is shall be completely voluntary and you therefore shall have a choice whether or not to disclose such additional information)</li>
	<li>Contact you or send you e-mail or other communications regarding updates on our website, new job opportunities, services and additional/new job postings/openings which may be of your interest</li>
	<li>Provide customer support and the services you request</li>
	<li>Ascertain how many people visit our website, of what kind and what areas they visit, on our website</li>
	<li>Resolve disputes, if any and troubleshooting</li>
	<li>Avoid/check illegal and/or potentially prohibited activities and to enforce Agreements</li>
	<li>Provide service updates and promotional offers related to our services/products</li>
	<li>Comply with any court judgment / decree / order / directive / legal &amp; government authority /applicable law</li>
	<li>Investigate potential violations or applicable national &amp; international laws</li>
	<li>Investigate deliberate damage to the website/services or its legitimate operation</li>
	<li>Detect, prevent, or otherwise address security and/or technical issues</li>
	<li>Protect the rights, property or safety of HTML and/or its Directors, employees and the general public at large</li>
	<li>Respond to Claims of third parties</li>
	<li>The members of our corporate family and group, affiliates, service providers and third parties under a contract to provide joint services, contents and marketing communications</li>
	<li>Other third parties to whom you explicitly require us to send the information</li>
</ol>
<p>If you consent to receive information about third party (such as employers, recruiters, data aggregators, marketers or others) opportunities, products or services/job opportunities or you make your profile visible we may disclose your information to such third parties for sending you communications via e-mail or otherwise to inform about new opportunities/services/products and new job postings/openings which may be of your interest. Also, we might use your personal information to communicate with you and ascertain if you are interested in third party services.</p>
<p>Your information shall be disclosed to our employees/service providers who provide services to us vis-a-vis our website and the services/products therein. These service providers/employees will have access to the information provided by you in order to perform their functions/services efficiently.</p>
<p>If you choose to use our referral service to tell a friend about our website or refer a job posting/service, we will ask you for your friend's name and email address. We will automatically send your friend an email inviting him or her to visit the website. However, your friend may contact us to request that he does not require such services/content/email or we remove the information related to him from our database.</p>
<p>Based upon the personally identifiable information you provide us, we will send you a welcoming email to verify your username and password. We will also communicate with you in response to your inquiries with respect to our services/content, to provide the services you request, and to manage your account. We will communicate with you by email or telephone, in accordance with your wishes. We will also send you SMS alerts from time to time to update you on new matched jobs and other updates.</p>
<p>In order to provide certain services to you, we may on occasion supplement the personal information you submitted to us with information from third party sources (third parties for this purpose may include our group / holding / subsidiary companies and or our service partners /associates). We reserve the right to disclose your personally identifiable information as required by law and when we believe that disclosure is necessary to protect our rights and/or to comply with a judicial proceeding, court order, or legal process served on our website.</p><br><br>
<p><strong>Resume Information</strong></p>
<p>Based on the profile status selected by you, your resume shall be accessible to potential employers. You can store your resume on our servers and make it searchable by third parties/employers/recruiters. You may only use it for applying online though our website and denying access to others.</p>
<p>If your profile status is visible, your resume is searchable and you make it non-confidential and visible to all and in such a case anyone can have access to your resume. If you keep your profile status anonymous, you opt to keep the resume confidential and then only those will have access to it to which you have applied for a job/opening.</p>
<p>We cannot guarantee that third parties shall gain access to your resume neither we are responsible for the use made of the resume by third parties to who you apply or who have access to our database, while your profile status has been made visible by you. In case of making your profile status visible, we are not responsible for the privacy, secrecy or retention of your resume.</p>
<p>You may edit, update and remove your resume at any time but parties who have access to our database (while your resume or profile was visible) may have retained a copy of your resume in their own files. We cannot be held responsible for such retention/storage. You should always remember that once you post your resume on our website with your profile visible, anybody will have access to the same and we do not have any control over such access and use of your resume/information by third parties. In case your profile status is anonymous and you apply for a job on our site, the prospective employer will also be able to retain a copy of your Resume and Profile.</p><br><br>
<p><strong>Changing Your Personal Information</strong></p>
<p>You can access and modify your personal information by signing on to the website. We will not modify the information provided by you. However, we recommend that you update your personal information as soon as such changes are necessitated.</p>
<p>Where you make a public posting, you may not be able to change or remove it nor shall you be able to close your account. Upon your request, we will close your account and remove your personal information from view as soon as reasonably possible, based on your account activity and in accordance with applicable law(s). However, we will retain your personal information from closed accounts to comply with law, Avoid/check illegal and/or potentially prohibited activities and to enforce User Agreements; Comply with any court judgment / decree / order / directive / legal &amp; government authority /applicable law; Investigate potential violations or applicable national &amp; international laws; Investigate deliberate damage to the website/services or its legitimate operation; Detect, prevent, or otherwise address security and/or technical issues; Protect the rights, property or safety of HTML and/or its Directors, employees and the general public at large; Respond to Claims of third parties; and take such other actions as may be permitted by law.</p><br><br>
<p><strong>Account Protection</strong></p>
<p>Your password is the key to your account. You shall be solely responsible for all the activities happening under your username and you shall be solely responsible for keeping your password secure. Do not disclose your password to anyone. If you share your password or your personal information with others, you shall be solely responsible for all actions taken under your username and you may lose substantial control over your personal information and may be subject to legally binding actions taken on your behalf. Therefore, if your password has been compromised for any reason, you should immediately change your password.</p><br><br>
<p><strong>Business Transaction</strong></p>
<p>In the event HTML goes through a business transition, such as a merger, acquisition by another company, or sale of all or a portion of its assets, your personally identifiable information will likely be among the assets transferred. Where your information is transferred you will be notified via email/prominent notice on our website for 30 days of any such change in ownership or control of your personal information.</p><br><br>
<p><strong>Security</strong></p>
<p>The security of your personal information is important to us. When you enter your personal information, we treat the data as an asset that must be protected and use tools (encryption, passwords, physical security, etc.) to protect your personal information against unauthorized access and disclosure. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure, therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security nor can we guarantee that third parties shall not unlawfully intercept or access transmissions or private communications, and that other users may abuse or misuse your personal information that you provide. Therefore, although we work hard to protect your information, we do not promise, and you should not expect, that your personal information or private communications will always remain private.</p><br><br>
<p><strong>Links to Other Sites</strong></p>
<p>The website contains links to other sites that are not owned or controlled by HT Media Limited Please be aware that we, HT Media Limited and/or the website, are not responsible for the privacy practices of such other sites.</p>
<p>We encourage you to be aware when you leave our site and to read the privacy statements of each and every Web-site that collects personally identifiable information.</p>
<p>This privacy statement applies only to information collected by the website or to our other related websites provided it appears at the footer of the page therein. It does not apply to third party advertisements which appear on our websites and we suggest you read the privacy statements of such advertisers.</p><br><br>
<p><strong>Changes in this Privacy Statement</strong></p>
<p>If we decide to change our privacy policy, we will post those changes to this privacy statement and such other places we deem appropriate so that you are updated about the manner we collect information, what information we collect, how we use it and under what circumstances, if any, we disclose it.</p>
<p>We reserve the right to modify this privacy statement at any time, so please review it frequently at Shine.com</p><br><br>
<p><strong>Contact Us</strong></p>
<p>If you have any questions or suggestions regarding our privacy policy, please contact us at: <a href="mailto:supun151515@gmail.com">support@synergy.lk</a> or <a href="mailto:supun@extremeits.biz">supun@extremeits.biz</a></p>
</div>


<?php
require_once("../php/footer.php")
?>
</body>
</html>